services:
  db:
    image: postgres:15-alpine
    container_name: ionbarber_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-ionbarber}
    # 🔴 PORTAS REMOVIDAS: O PostgreSQL agora está isolado e invisível para a internet!
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-user} -d ${POSTGRES_DB:-ionbarber}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: ionbarber_backend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./backend/.env # 🔥 Todos os segredos serão injetados por este ficheiro